import { PageLayout } from "@/components/PageLayouts";
import Head from "next/head";
import useSWR from "swr";
import { fetcher } from "@/utils/api";

export default function Home() {
  const { data, error, isLoading } = useSWR("/data", fetcher);

  return (
    <>
      <Head>
        <title>React and charts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>hello</PageLayout>
    </>
  );
}
