import { InferGetStaticPropsType } from "next";
import { DashboardLayout } from "@/components/layouts/DashboardLayouts";
import { Dashboard } from "@/components/Dashboard";
import Head from "next/head";
import { SWRConfig } from "swr/_internal";
import { getExampleData } from "@/apis/exampleData";

export async function getStaticProps() {
  let data;

  try {
    data = await getExampleData();
  } catch {
    data = {
      stocks: [],
      dataset: 0,
    };
  }

  return {
    props: {
      fallback: {
        "/example-data": data,
      },
    },
  };
}

export default function Home({
  fallback,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>React and charts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SWRConfig value={{ fallback }}>
        <DashboardLayout>
          <Dashboard />
        </DashboardLayout>
      </SWRConfig>
    </>
  );
}
